title: CV | Sunjae Lee
description:  "Sunjae Lee's CV"
url: https://urbanin-sj.github.io
baseurl: "/about"
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
